### ISSUE TITLE
Typo in package.json

### ISSUE THREAD

**Issue by ivany4** [rubenspgcavalcante/react-leaflet-ant-path#1]
It seems that there's a typo in package.json (key named `perDependencie` instead of `peerDependencies`). As a result, npm does not ask to install peer packages.

**Comment by ivany4** [comment]
@rubenspgcavalcante, just noticed, there's the same [typo in leaflet-ant-path](https://github.com/rubenspgcavalcante/leaflet-ant-path/blob/a05f1501499d03e841c11cbffd24be3bfeae3825/package.json#L34), should I open another issue in that project? :)
Thanks for your work, btw!

**Comment by rubenspgcavalcante** [comment]
Yes, for sure! :)
Thanks for contributing also! :D

**Comment by rubenspgcavalcante** [comment]
Closed by #4
